version: '3.9'
services:
  orders:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    ports:
    - 8080:8080
    container_name: orders
    depends_on:
      - orders-db
  orders-db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    container_name: orders-db
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres