apiVersion: v1
kind: Namespace
metadata:
  name: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
  namespace: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
    spec:
      restartPolicy: Always
      containers:
        - name: orders
          image: lilty/cavvar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
  namespace: order-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: orders
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
        - name: orders-db
          image: postgres
          env:
            - name: POSTGRES_DB
              value: orders_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - name: postgres
              containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  labels:
    name: orders-db
  namespace: order-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: orders-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    name: jaeger
  namespace: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger
  template:
    metadata:
      labels:
        name: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 16686
            - containerPort: 5778
            - containerPort: 14268
            - containerPort: 14250
            - containerPort: 9411
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    name: jaeger
  namespace: order-service
spec:
  ports:
    - port: 16686
      name: frontend
      targetPort: 16686
    - port: 5778
      name: agent-config
      targetPort: 5778
    - port: 14268
      name: collector-jaeger-thrift
      targetPort: 14268
    - port: 14250
      name: collector-accept-model-proto
      targetPort: 14250
    - port: 9411
      name: collector-zipkin-endpoint
      targetPort: 9411
    - port: 5775
      protocol: UDP
      name: agent-zipkin-thrift
      targetPort: 5775
    - port: 6831
      protocol: UDP
      name: agent-jaeger-thrift
      targetPort: 6831
    - port: 6832
      protocol: UDP
      name: agent-jaeger-thrift-two
      targetPort: 6832
  selector:
    name: jaeger